### PR TITLE
default-target-platform

### PR DESCRIPTION
**Pull request by brunogabriel**
#COMMENTS
* Remove Platform avoiding Fii import in web

### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dev/documentation/dio/latest/)
- [x] I have searched for a similar pull request in the [project](https://github.com/cfug/dio/pulls) and found none
- [x] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [ ]  I have added the required tests to prove the fix/feature I'm adding
- [x] I have updated the documentation (if necessary)
- [x] I have run the tests without failures
- [ ] I have updated the `CHANGELOG.md` in the corresponding package

### Additional context and info (if any)

Using defaultTargetPlatform to avoid fii imports in web projects.

### CODE REVIEW

**Comment by kuhnroyal** [comment]
@ueman The native adapter already depends on Flutter doesn't it?
@brunogabriel Can you provide a little bit more context? You should never have the native adapter in any web builds.

**Comment by brunogabriel** [comment]
> @ueman The native adapter already depends on Flutter doesn't it? @brunogabriel Can you provide a little bit more context? You should never have the native adapter in any web builds.

Hi, @ueman  thanks for ask, yeah, I believe that NativeAdapter is not used for web apps, but I was testing my implementation ran by accident on flutter web and application suddenly broken by imports (fii). My idea here is to avoid this scenario.

**Comment by ueman** [comment]
> @ueman The native adapter already depends on Flutter doesn't it?

True, I missed that.

> defaultTargetPlatform is a get (final), right?

Kinda, it can be overriden via `debugDefaultTargetPlatformOverride`.

> My idea here is to avoid this scenario.

`defaultTargetPlatform` defaults to `TargetPlatform.android`, as stated in the docs:

> In a test environment, the platform returned is [TargetPlatform.android](https://api.flutter.dev/flutter/foundation/TargetPlatform.html) regardless of the host platform.

**Comment by kuhnroyal** [comment]
Thanks for the context!
From my understanding, `TargetPlatform` is mostly used for theming etc. and we should not rely on it for implementation details. I think you should be able to fix this by adjusting your adapter instantiation.

Alternatively we could think about using https://pub.dev/packages/platform - not sure how established this is.

**Comment by brunogabriel** [comment]
> > @ueman The native adapter already depends on Flutter doesn't it?
> 
> True, I missed that.
> 
> > defaultTargetPlatform is a get (final), right?
> 
> Kinda, it can be overriden via `debugDefaultTargetPlatformOverride`.
> 
> > My idea here is to avoid this scenario.
> 
> `defaultTargetPlatform` defaults to `TargetPlatform.android`, as stated in the docs:
> 
> > In a test environment, the platform returned is [TargetPlatform.android](https://api.flutter.dev/flutter/foundation/TargetPlatform.html) regardless of the host platform.

do you suggest another approach? i know that this code isn't for web in this adapter, but the goal is to avoid this situation.

**Comment by brunogabriel** [comment]
> Thanks for the context!
> From my understanding, `TargetPlatform` is mostly used for theming etc. and we should not rely on it for implementation details. I think you should be able to fix this by adjusting your adapter instantiation.
> 
> Alternatively we could think about using https://pub.dev/packages/platform - not sure how established this is.

yeah, understood, i got this behavior by accident in multiOS app, in my DI i can provide using simple chec. I'll read this lib tks

**Comment by brunogabriel** [comment]
> Thanks for the context!
> From my understanding, `TargetPlatform` is mostly used for theming etc. and we should not rely on it for implementation details. I think you should be able to fix this by adjusting your adapter instantiation.
> 
> Alternatively we could think about using https://pub.dev/packages/platform - not sure how established this is.

another approach, i thought it's create a wrapper.

**Comment by ueman** [comment]
Honestly, I wouldn't change anything and reject this PR. This package is not intended to be run on web and it also states so on pub.dev. The decision to use the native adapter should be done in the code of the consumer of this package.

**Comment by kuhnroyal** [comment]
I agree.
@brunogabriel You should be able to extract your Dio configuration to 2 separate files based on the platform and then use a conditional import similar to https://github.com/cfug/dio/blob/main/dio/lib/src/adapter.dart#L6

**Pull request closed without merging**
