### PR TITLE
Actually run all test in the baseline 🙈

### PR DESCRIPTION
**Pull request by kuhnroyal**
Trying to fix the wrong coverage for http2 plugin.

### New Pull Request Checklist

- [ ] I have read the [Documentation](https://pub.dev/documentation/dio/latest/)
- [ ] I have searched for a similar pull request in the [project](https://github.com/cfug/dio/pulls) and found none
- [ ] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [ ] I have added the required tests to prove the fix/feature I'm adding
- [ ] I have updated the documentation (if necessary)
- [ ] I have run the tests without failures
- [ ] I have updated the `CHANGELOG.md` in the corresponding package

### CODE REVIEW

**Comment by kuhnroyal** [comment]
I don't understand this, locally I get the same coverage as in the baseline.

**Comment by kuhnroyal** [comment]
Nvm, found it...
After this is merged, we should have a correct baseline.

**Review by AlexV525 — APPROVED** [review]

**Comment by AlexV525** [comment]
I've been seeing the same exception multiple times, is that a known issue?

https://github.com/cfug/dio/actions/runs/9404023625/job/25901960393

**Comment by kuhnroyal** [comment]
Yea, this is likely related to the old melos version that we have to use on min SDK.

**Comment by AlexV525** [comment]
> Yea, this is likely related to the old melos version that we have to use on min SDK.

Ah I remember I saw the same reply from you somewhere before, damn...

**Pull request merged**
