### PR TITLE
Merge main into 6.0.0

### PR DESCRIPTION
**Pull request by kuhnroyal**
Merge main into 6.0.0

### CODE REVIEW

**Review by AlexV525 — APPROVED** [review]

**Comment by AlexV525** [comment]
I'm curious: You have permission for branches, why do we create the PR instead? 😄

**Comment by kuhnroyal** [comment]
Because I usually mess up the merges as you can see :D

**Comment by kuhnroyal** [comment]
The failing tests seem to be unrelated.

**Comment by kuhnroyal** [comment]
Hmm we don't actually want to squash this right... ?

**Comment by AlexV525** [comment]
Yeah and sorry for the delay I was busy participating in our I/O Connect event.

**Comment by kuhnroyal** [comment]
But now you squashed it :D

**Comment by AlexV525** [comment]
Ehh, did I? It should be a merge commit

**Comment by kuhnroyal** [comment]
Ah right, sorry

**Pull request merged**
