### PR TITLE
👷 Add `README.md` & `CHANGELOG.md` size check for publishable tests

### PR DESCRIPTION
**Pull request by AlexV525**
Inspired by https://github.com/dart-lang/pub-dev/issues/6012.

### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dev/documentation/dio/latest/)
- [x] I have searched for a similar pull request in the [project](https://github.com/cfug/dio/pulls) and found none
- [x] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [ ] I have added the required tests to prove the fix/feature I'm adding
- [ ] I have updated the documentation (if necessary)
- [x] I have run the tests without failures
- [ ] I have updated the `CHANGELOG.md` in the corresponding package

### CODE REVIEW

**Comment by AlexV525** [comment]
Yeah, a working example is here: https://github.com/cfug/dio/actions/runs/6269325403/job/17025585341?pr=1977

**Comment by ueman** [comment]
How big are our changelog and readme files right now?

**Comment by AlexV525** [comment]
> How big are our changelog and readme files right now?

Quite far from the limit. And now we have separated docs, which decreases the risk of reaching the limit.
image

**Review by ueman — APPROVED** [review]

**Comment by AlexV525** [comment]
> How big are our changelog and readme files right now?

Now they are displayed in each run. https://github.com/cfug/dio/actions/runs/6270605319/job/17028785303?pr=1977

**Pull request merged**
