### PR TITLE
[native_dio_adapter] Fix `onReceiveProgress` callback.

### PR DESCRIPTION
**Pull request by Vovcharaa**
Part of #1835 

### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dev/documentation/dio/latest/)
- [x] I have searched for a similar pull request in the [project](https://github.com/cfug/dio/pulls) and found none
- [x] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [x] I have added the required tests to prove the fix/feature I'm adding
- [ ] I have updated the documentation (if necessary)
- [ ] I have run the tests without failures
- [x] I have updated the `CHANGELOG.md` in the corresponding package

### CODE REVIEW

**Comment by ueman** [comment]
Hey, thanks for doing this. Can you add a test for this change?

**Comment by Vovcharaa** [comment]
@ueman done

**Comment by Vovcharaa** [comment]
@ueman This pr only fixes `onReceiveProgress` in `download` method.
Native and http2 adapter do not implement `onReceiveProgress` and `onSendProgress` at all.

**Comment by ueman** [comment]
> @ueman This pr only fixes `onReceiveProgress` in `download` method. Native and http2 adapter do not implement `onReceiveProgress` and `onSendProgress` at all.

Yeah that's fine. It's already better than before, even if not everything works.

**Review by ueman — APPROVED** [review]

**Pull request merged**
