### PR TITLE
✨ `ImplyContentTypeInterceptor`

### LINKED ISSUE #1667: Restore content-type auto-detection and only optionally disable it
### Request Statement

Hi,
in release 5.0.0 the content-type auto-detection logic. This seriously impact many applications relying on that logic (which, for many use-cases, was correct). SInce it was already possible to force manually content-type, would'nt be possible to specify a constructor flag in Dio to trigger the new logic and let the old one works flawlessly for compatibility with all existing code ?

Thank you,

### Solution Brainstorm

Pass parameter on constructor to explicitly disable the content-type auto-guess logic.

### PR DESCRIPTION
**Pull request by AlexV525**
Reverts the functionality of cfug/diox#69.

Resolves #1667 #1661 #1653 #1650 #1648 #1646

### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dev/documentation/dio/latest/)
- [x] I have searched for a similar pull request in the [project](https://github.com/cfug/dio/pulls) and found none
- [x] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [x] I have added the required tests to prove the fix/feature I'm adding
- [x] I have updated the documentation (if necessary)
- [x] I have run the tests without failures

### Additional context and info (if any)

- The interceptor can be removed by calling `Interceptor.removeImplyContentTypeInterceptor`.
- The interceptor was intended not to be exposed to outside usages.

### CODE REVIEW

**Comment by naamapps** [comment]
In my case if the body data is a Map then I want the content type to be implied as `application/json`, not `application/x-www-form-urlencoded`.
Can you please explain the decision to use `formUrlEncodedContentType` when the data is a Map?

**Comment by AlexV525** [comment]
> Can you please explain the decision to use `formUrlEncodedContentType` when the data is a Map?

https://github.com/cfug/dio/blob/ac78e6151e1736f945cb9b215bbcfac230e19cf1/dio/lib/src/transformer.dart#L72-L85

**Comment by AlexV525** [comment]
> In my case if the body data is a Map then I want the content type to be implied as `application/json`, not `application/x-www-form-urlencoded`.

You'll need to set as the JSON type in your case, which is the same before 5.0.0.

**Review by talisk — APPROVED** [review]
🚀

**Pull request merged**
