### PR TITLE
Use StreamedRequest with onSendProgress in adapter

### LINKED ISSUE #1835: native_dio_adapter does not support onReceiveProgress and onSendProgress
### Package

native_dio_adapter

### Version

0.1.0

### Output of `flutter doctor -v`

```shell
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.4 22F66 darwin-arm64, locale en-UA)
    • Flutter version 3.10.1 on channel stable at /Users/vovchara/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (10 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/vovchara/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Dart Version

3.0.1

### Steps to Reproduce

Provide `onReceiveProgress` and/or `onSendProgress` callback to any request method.

### Expected Result

Callback is called the same way as without native adapter.

### Actual Result

Callback is called only once after download is done.

### PR DESCRIPTION
**Pull request by Vovcharaa**
Fix #1835

### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dev/documentation/dio/latest/)
- [x] I have searched for a similar pull request in the [project](https://github.com/cfug/dio/pulls) and found none
- [x] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [ ] I have added the required tests to prove the fix/feature I'm adding
- [ ] I have updated the documentation (if necessary)
- [ ] I have run the tests without failures
- [ ] I have updated the `CHANGELOG.md` in the corresponding package

### CODE REVIEW

**Comment by SpeedReach** [comment]
Hello are you still working on this issue?  I could complete this if you're too busy.

**Comment by Vovcharaa** [comment]
> Hello are you still working on this issue? I could complete this if you're too busy.

You can take the lead in finalizing this feature.
But it is not possible to finish it right now. Check this https://github.com/dart-lang/http/issues/997.
StreamSink in `cupertino_http` is buffering data and I don't know how to prevent this behavior so this feature won`t work as intended. This must be handled on the `cupertino_http` side.

**Comment by SpeedReach** [comment]
I just tested with a larger data (more than 1024 bytes) according to https://github.com/dart-lang/http/issues/997#issuecomment-1678108093
and  it works fine.
```dart
  final dio = Dio()..httpClientAdapter = NativeAdapter();
  String superLargeData = 'aaa';
  for(int i=0;i<1000;i++){
    superLargeData += 'wwwww';
  }
  final res = await dio.post(
      "url",
      data: superLargeData,
      onSendProgress: (a,b){
        print('$a $b');
      }
  );
```

output:
```
flutter: 1024 5003
flutter: 2048 5003
flutter: 3072 5003
flutter: 4096 5003
flutter: 5003 5003
```

**Comment by AlexV525** [comment]
@Vovcharaa Are you still on this?
@SpeedReach If you want to continue based on the current work, please merge previous commits into your new branch to keep everyone's contributions recorded. Thanks.

**Comment by SpeedReach** [comment]
The changes @Vovcharaa made already completes the issue, but he didn't test it with data larger than the buffer, so he thought it didn't work.
This branch can be merged directly I think.

**Comment by AlexV525** [comment]
I looked at the implementation again and found I did the same thing in the new adapter. This can be easily addressed once we switch to the new adapter #1976.

**Pull request closed without merging**
