### PR TITLE
Transfer more tests to shared test project

### PR DESCRIPTION
**Pull request by kuhnroyal**
This PR transfers some download and header/options tests to the shared test project and thus enabled them for the Http2 adapter.

### New Pull Request Checklist

- [ ] I have read the [Documentation](https://pub.dev/documentation/dio/latest/)
- [ ] I have searched for a similar pull request in the [project](https://github.com/cfug/dio/pulls) and found none
- [ ] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [ ] I have added the required tests to prove the fix/feature I'm adding
- [ ] I have updated the documentation (if necessary)
- [ ] I have run the tests without failures
- [ ] I have updated the `CHANGELOG.md` in the corresponding package

### CODE REVIEW

**Review by AlexV525 — APPROVED** [review]

**Comment by AlexV525** [comment]
https://github.com/cfug/dio/actions/runs/8513054967/job/23315952339#step:15:121

```console
[dio]: ::group::❌ loading test/test_suite_test.dart (failed)
[dio]: Failed to load "test/test_suite_test.dart":
[dio]: ../../../../.pub-cache/git/dio-1c2843a2fab1c3795272df1e81502616761e192e/dio_test/lib/src/test/upload_tests.dart:66:20: Error: No named parameter with the name 'exclusive'.
[dio]:       f.createSync(exclusive: false);
[dio]:                    ^^^^^^^^^
[dio]: ../../../../.pub-cache/git/dio-1c2843a2fab1c3795272df1e81502616761e192e/dio_test/lib/src/test/upload_tests.dart:95:20: Error: No named parameter with the name 'exclusive'.
[dio]:       f.createSync(exclusive: false);
[dio]:                    ^^^^^^^^^
```

**Comment by kuhnroyal** [comment]
I think this is happening due to the git dependency.

**Comment by AlexV525** [comment]
We can also remove the `exclusive` since it defaults to `false`.

**Comment by kuhnroyal** [comment]
Yea but that doesn't really fix the issue, only the current symptom.

Something else is wrong here, I played around in https://github.com/kuhnroyal/dio/pull/28 and the stable workflow failed with analyzer errors that I have fixed in the same PR. Like it is analyzing an older dio version. Not sure. 

In any case, the http package is doing using a similar approach and they have their test package in the main pubspec as path dependency: https://github.com/dart-lang/http/blob/master/pkgs/http/pubspec.yaml
I think that's what we need to go back.

**Pull request merged**
