### PR TITLE
Migrate tests from httpbin to httpbun

### PR DESCRIPTION
**Pull request by kuhnroyal**
### New Pull Request Checklist

- [ ] I have read the [Documentation](https://pub.dev/documentation/dio/latest/)
- [ ] I have searched for a similar pull request in the [project](https://github.com/cfug/dio/pulls) and found none
- [ ] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [ ] I have added the required tests to prove the fix/feature I'm adding
- [ ] I have updated the documentation (if necessary)
- [ ] I have run the tests without failures
- [ ] I have updated the `CHANGELOG.md` in the corresponding package

### CODE REVIEW

**Comment by kuhnroyal** [comment]
This does not work for chrome platform or TLS tests....

**Comment by kuhnroyal** [comment]
@cfug/devs `httpbin` has been unreliable for almost 2 weeks now and it is unmaintained. I discovered https://github.com/sharat87/httpbun while looking for alternatives.
I mostly adapted our tests and there are 2 things that we need to check.

1. The `upload_stream_test.dart` currently fails because `httpbun` seems to return the binary upload data as a string which I seem to be unable to compare to the original - see https://github.com/sharat87/httpbun/issues/5
2. The http2 pinning test fails

Looking for thoughts and ideas.

**Comment by kuhnroyal** [comment]
Some chrome tests are still failing because of https://github.com/sharat87/httpbun/issues/6

**Comment by kuhnroyal** [comment]
@cfug/devs This looks good now, the Dart 2.15 failures are unrelated.

**Review by ueman — APPROVED** [review]
LGTM, thanks for fixing

**Pull request merged**
