### PR TITLE
Fix: example queued_interceptor_csrftoken.dart

### PR DESCRIPTION
**Pull request by seunghwanly**
Provide a more suitable example for queued_interceptor_csrftoken.dart

### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dev/documentation/dio/latest/)
- [x] I have searched for a similar pull request in the [project](https://github.com/cfug/dio/pulls) and found none
- [x] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [ ] I have added the required tests to prove the fix/feature I'm adding
- [ ] I have updated the documentation (if necessary)
- [x] I have run the tests without failures
- [ ] I have updated the `CHANGELOG.md` in the corresponding package

### Additional context and info (if any)

This example adds 2 different `QueuedInterceptorsWrapper` and the last one handles `onError` to update csrf token.

---

fixes #2128

### CODE REVIEW

**Comment by seunghwanly** [comment]
I'll check the type exceptions in `test_suite_test.dart`

**Comment by AlexV525** [comment]
The failing tests should be random, caused by the httpbun, fyi.

**Review by AlexV525 — APPROVED** [review]
Someday we'd expect to have a unit test with token updates.

**Comment by seunghwanly** [comment]
> Someday we'd expect to have a unit test with token updates.

I'll also be on the lookout for cases to write unit tests for token refresh.

**Pull request merged**
