### PR TITLE
fix(develop): HTTP/2 error: Stream error #486

### PR DESCRIPTION
**Pull request by xrr2016**
### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dartlang.org/packages/dio)
- [x] I have searched for a similar pull request in the [project](https://github.com/flutterchina/dio/pulls) and found none
- [x] I have updated this branch with the latest `develop` to avoid conflicts (via merge from master or rebase)
- [x] I have added the required tests to prove the fix/feature I am adding
- [x] I have updated the documentation (if necessary)
- [x] I have run the tests and they pass

This merge request fixes / refers to the following issues: ...

### Pull Request Description

Fix DioError [DioErrorType.DEFAULT]: HTTP/2 error: Stream error: Stream was terminated by peer (errorCode: 1)

### Ref

https://github.com/dart-lang/http2/issues/49

https://github.com/flutterchina/dio/issues/486

### CODE REVIEW

**Comment by itsbalamurali** [comment]
@ueman @kuhnroyal can you please review this and merge it?

**Review by amondnet — APPROVED** [review]

**Comment by Nobler** [comment]
By the way, some unit tests should be added for sure.

**Comment by SahajRana** [comment]
This PR does not resolve the issue from what I can see.

**Comment by AlexV525** [comment]
Hi everyone! We've made our hardfork repo public and published a new version of `dio`, named `diox`.
The new package contains the PR of the fix.
Please refer to https://pub.dev/packages/diox/versions/5.0.0-dev.1 to use the fork.
You can also see why we're working for a hardfork at https://github.com/cfug/diox/issues/29 and https://github.com/flutterchina/dio/issues/1607.

**Pull request closed without merging**
