### PR TITLE
feat(native_dio_adapter): bump cronet_http dependency

### PR DESCRIPTION
**Pull request by dkrutskikh**
### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dev/documentation/dio/latest/)
- [x] I have searched for a similar pull request in the [project](https://github.com/cfug/dio/pulls) and found none
- [x] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [x] I have added the required tests to prove the fix/feature I'm adding
- [x] I have updated the documentation (if necessary)
- [x] I have run the tests without failures
- [x] I have updated the `CHANGELOG.md` in the corresponding package

### CODE REVIEW

**Review by ueman — APPROVED** [review]
Thanks!

**Comment by ueman** [comment]
@dkrutskikh Is the lint upgrade the reason for the new lint failures?

**Comment by dkrutskikh** [comment]
@ueman I was revert lints package version

**Comment by ueman** [comment]
Apparently it was not the reason. The failures are unrelated. Thanks again!

**Pull request merged**
