### PR TITLE
[http2_adapter] ✨ Support non-TLS connection requests

### LINKED ISSUE #1983: [BUG] [dio_http2_adapter] WRONG_VERSION_NUMBER tls_record.cc:231
### Package

http2_adapter

### Version

2.3.1+1

### Operating-System

Windows

### Output of `flutter doctor -v`

```shell
[√] Flutter (Channel stable, 3.13.5, on Microsoft Windows [Version 10.0.22621.2283], locale en-US)
    • Flutter version 3.13.5 on channel stable at c:\dev\flutter\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (8 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34031.279
    • Windows 10 SDK version 10.0.22621.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2283]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 117.0.5938.92
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 117.0.2045.36

[√] Network resources
    • All expected network resources are available.
```

### Dart Version

3.1.2

### Steps to Reproduce

Client works well without Http2Adapter on Windows and Web, but fails on Windows with Http2Adapter 

```dart
    _dio = Dio()
      ..options.baseUrl = '${host.url}/api/Files'
      ..interceptors.add(LogInterceptor())
      ..interceptors.add(
        InterceptorsWrapper(
          onRequest: (options, handler) async {
            final token = await getToken();
            options.headers['Authorization'] = 'Bearer $token';
            handler.next(options);
          },
        ),
      );

    _dio.httpClientAdapter = Http2Adapter(
      ConnectionManager(
        idleTimeout: const Duration(seconds: 15),
        onClientCreate: (_, config) => config.onBadCertificate = (_) => true,
      ),
    );

    final multipartFile = MultipartFile.fromStream(
      () => file.fileStream,
      file.fileSize,
      filename: file.fileName,
    );

    final response = await _dio.post<ResponseBody>(
      '/upload_file',
      data: FormData.fromMap({
        'file': multipartFile,
      }),
      cancelToken: cancelToken,
      options: Options(responseType: ResponseType.stream),
    );
```

.Net Core service endpoints
```json
"Kestrel": {
  "Endpoints": {
    "gRPC": {
      "Protocols": "Http2",
      "Url": "http://+:7000"
    },
    "gRPC-test": {
      "Protocols": "Http1AndHttp2",
      "Url": "http://+:7001"
    }
  }
}
```

### Expected Result

It could be nice if client will work on Windows with Http2Adapter 
Client works well without Http2Adapter on Windows and Web (port 7001), but fails on Windows with Http2Adapter.
Http2Adapter throws exception: WRONG_VERSION_NUMBER tls_record.cc:231

### Actual Result

```
uri: http://localhost:7000/api/Files/upload_file
flutter: DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error:
	WRONG_VERSION_NUMBER(../../third_party/boringssl/src/ssl/tls_record.cc:231))
```

### PR DESCRIPTION
**Pull request by AlexV525**
Fixes #1983.

### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dev/documentation/dio/latest/)
- [x] I have searched for a similar pull request in the [project](https://github.com/cfug/dio/pulls) and found none
- [x] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [x] I have added the required tests to prove the fix/feature I'm adding
- [x] I have updated the documentation (if necessary)
- [x] I have run the tests without failures
- [x] I have updated the `CHANGELOG.md` in the corresponding package

### CODE REVIEW

**Review by kuhnroyal — APPROVED** [review]
Do we need to worry about redirects between http/https?

**Comment by AlexV525** [comment]
> Do we need to worry about redirects between http/https?

Don't worry, it will create new connections.

**Comment by AlexV525** [comment]
> @AlexV525 I built my app with latest main and can confirm this fixes the bug my app was encountering. Thank you. When do you think this fix will be released (assuming in 5.3.5 release).

Thanks for your rapid testing. It'll generally takes days or weeks before we make a new release, depend on the overall status of packages.

**Comment by farrukhnajmi** [comment]
@AlexV525 latest dev build  of my app with main branch of dio repo is giving a new error now. Note that the host  is same as I was using before and I will send it to you privately.

I/flutter (15768): ╔╣ DioError ║ DioExceptionType.connectionError
I/flutter (15768): ║  The connection errored: Failed host lookup: '<my host I will send you privately>' This indicates an error which most likely cannot be solved by the library.
I/flutter (15768): ╚══════════════════════════════════════════════════════════════════════════════════════════╝
E/flutter (15768): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DioException [connection error]: The connection errored: Failed host lookup: <my host I will send you privately>' This indicates an error which most likely cannot be solved by the library.
E/flutter (15768): Error: SocketException: Failed host lookup: '<my host I will send you privately>' (OS Error: No address associated with hostname, errno = 7)
E/flutter (15768): #0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:507)
E/flutter (15768): #1      _FutureListener.handleError (dart:async/future_impl.dart:180)
E/flutter (15768): #2      Future._propagateToListeners.handleError (dart:async/future_impl.dart:858)
E/flutter (15768): #3      Future._propagateToListeners (dart:async/future_impl.dart:879)
E/flutter (15768): #4      Future._completeError (dart:async/future_impl.dart:655)
E/flutter (15768): #5      _SyncCompleter._completeError (dart:async/future_impl.dart:63)
E/flutter (15768): #6      _Completer.completeError (dart:async/future_impl.dart:27)
E/flutter (15768): #7      Future.any.onError (dart:async/future.dart:618)
E/flutter (15768): #8      _RootZone.runBinary (dart:async/zone.dart:1666)
E/flutter (15768): #9      _FutureListener.handleError (dart:async/future_impl.dart:177)
E/flutter (15768): #10     Future._propagateToListeners.handleError (dart:async/future_impl.dart:858)
E/flutter (15768): #11     Future._propagateToListeners (dart:async/future_impl.dart:879)
E/flutter (15768): #12     Future._completeError (dart:async/future_impl.dart:655)
E/flutter (15768): #13     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:556)
E/flutter (15768): #14     _microtaskLoop (dart:async/schedule_microtask.dart:40)
E/flutter (15768): #15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

**Comment by AlexV525** [comment]
> @AlexV525 latest dev build of my app with main branch of dio repo is giving a new error now. Note that the host is same as I was using before and I will send it to you privately. Please let me know if you would like me to test with any branch code.

Received. You mean using the http2 adapter?

**Comment by farrukhnajmi** [comment]
I am not explicitly using the http2 adapter. Here is what my code look like to make a REST call to my service:

```
MyClient createClient(MyConfig myConfig) {
  final Dio dio = Dio()..options = BaseOptions(baseUrl: myConfig.url); // Provide a dio instance

  // customization to log requests and responses
  dio.interceptors.add(PrettyDioLogger(
      requestHeader: true,
      requestBody: true,
      responseBody: true,
      responseHeader: false,
      error: true,
      compact: true,
      maxWidth: 90));
  return MyClient(dio);
}
```

MyClient class is an abstract class with @RestApi() annotation from retrofit:

```
import 'package:retrofit/http.dart';
import 'package:retrofit/retrofit.dart';
```

Retrofit generates the concrete class from the abstract class. The generated class uses Dio.fetch(...) to make GET and POST calls.

**Comment by AlexV525** [comment]
From your info, there is nothing related to the current session. Please submit new issues with a minimal reproducible example.

**Pull request merged**
