### PR TITLE
Improve docs for LogInterceptor

### LINKED ISSUE #1970: LogInterceptor causes connection loss in Flutter version 3.13.x
### Package

dio

### Version

5.2.1+1

### Operating-System

iOS

### Output of `flutter doctor -v`

```shell
[!] Flutter (Channel [user-branch], 3.13.4, on macOS 13.0.1 22A400 darwin-arm64,
    locale en-IN)
    ! Flutter version 3.13.4 on channel [user-branch] at
      /Users/prajapati.c001/development/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an
      official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions
      at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss
      this error.
    • Framework revision 367f9ea16b (5 days ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/prajapati.c001/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/prajapati.c001/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • testers’s iPhone (mobile) • 00008110-001565341E78401E • ios            •
      iOS 16.6.1 20G81
    • macOS (desktop)           • macos                     • darwin-arm64   •
      macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)              • chrome                    • web-javascript •
      Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### Dart Version

3.1.2

### Steps to Reproduce

1. Implement log interceptor for your app
2. send requests to multiple endpoints that return long responses
3. Wait for log "lost connection to device"

---

### OR when you change package code

Cause:
[https://github.com/cfug/dio/blob/main/dio/lib/src/interceptors/log.dart#L138C19](https://github.com/cfug/dio/blob/main/dio/lib/src/interceptors/log.dart#L138C19)

Fix:
```dart
// Note you need to import debugPrint. import 'package:flutter/foundation.dart' show debugPrint;
debugPrint(object.toString());
```

### Expected Result

The log interceptor shouldn't fail, and the device shouldn't lose connection.

### Actual Result

Can't paste whole logs because of company policy,
Screenshot 2023-09-18 at 11 38 21 AM

### PR DESCRIPTION
**Pull request by kuhnroyal**
* closes #1970

### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dev/documentation/dio/latest/)
- [x] I have searched for a similar pull request in the [project](https://github.com/cfug/dio/pulls) and found none
- [x] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [ ] I have added the required tests to prove the fix/feature I'm adding
- [x] I have updated the documentation (if necessary)
- [ ] I have run the tests without failures
- [ ] I have updated the `CHANGELOG.md` in the corresponding package

### CODE REVIEW

**Review by ueman — APPROVED** [review]
Dang, good catch

**Comment by ueman** [comment]
Was there a reason we're not using `dart:developer log()`?

**Comment by kuhnroyal** [comment]
History show it has always used `print`. I never directly used `dart:developer log()`, not sure how this differs from `debugPrint`.

**Comment by ueman** [comment]
> History show it has always used `print`. I never directly used `dart:developer log()`, not sure how this differs from `debugPrint`.

`log` isn't throttled, but it only prints during debug mode, but not during release mode.

**Comment by AlexV525** [comment]
I've been using `log` for a while, it is unthrottled, but it still regress performance for massive contents. And sometimes people want logs visible from the native side (e.g. logcat). We can recommend it too in docs and comments though.

**Comment by AlexV525** [comment]
> @AlexV525 Can you help out with the Chinese translation please :)

Looks like we can have more modifications, I'll wait until then.

**Review by ueman — APPROVED** [review]

**Pull request merged**
